### ISSUE TITLE
I have a redirect problem

### ISSUE THREAD

**Issue by Haksiu** [stuyy/discord-oauth2-example#1]
Hey, I have a redirect problem.
Error:
```
TokenError
    at Strategy.OAuth2Strategy.parseErrorResponse (C:\Users\haksi\Desktop\Programming\Projects\DiscordJS\WebDashboard\node_modules\passport-oauth2\lib\strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (C:\Users\haksi\Desktop\Programming\Projects\DiscordJS\WebDashboard\node_modules\passport-oauth2\lib\strategy.js:405:16)
    at C:\Users\haksi\Desktop\Programming\Projects\DiscordJS\WebDashboard\node_modules\passport-oauth2\lib\strategy.js:175:45
    at C:\Users\haksi\Desktop\Programming\Projects\DiscordJS\WebDashboard\node_modules\oauth\lib\oauth2.js:191:18
    at passBackControl (C:\Users\haksi\Desktop\Programming\Projects\DiscordJS\WebDashboard\node_modules\oauth\lib\oauth2.js:132:9)
    at IncomingMessage.<anonymous> (C:\Users\haksi\Desktop\Programming\Projects\DiscordJS\WebDashboard\node_modules\oauth\lib\oauth2.js:157:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)```

**Comment by Connorseds2002** [comment]
From what I can see from what it looked to be from what I can see in the console as I am getting the same error 

It looks to the database that the user data is being saved to

**Comment by CRZA5** [comment]
Probably issue is with your strategy file. Re-clone it and try

**Comment by TorJonasHansen** [comment]
I get his too even when i just downloaded what @stuyy made, no matter what i try it always return this

**Comment by TorJonasHansen** [comment]
It looks like this have something to do with saving the use to the request, because if u use done(null, null) which just skips saving the user doesnt return this error

**Comment by TorJonasHansen** [comment]
@Haksiu Add this, it woorks for me atleast:

```
passport.serializeUser(function(user, done) {
    done(null, user);
});
  
passport.deserializeUser(function(user, done) {
    done(null, user);
});
```

**Comment by izumi-06** [comment]
@Haksiu This workes for me

```
const DiscordStragegy = require("passport-discord").Strategy
const passport = require("passport")

passport.serializeUser(function(user, done) {
    done(null, user);
});
  
passport.deserializeUser(function(user, done) {
    done(null, user);
});

passport.use(new DiscordStragegy({
    clientID: process.env.CLIENT_ID,
    clientSecret: process.env.CLIENT_SECRET,
    callbackURL: process.env.CLIENT_REDIRECT,
    scope: ["identify", "guilds"]
}, (accessToken, refreshToken, profile, done) => {
    done(null, profile)
}))
```
